// Classify an inbound message that landed in a campaign thread.
//
// A thread we started collects everything that comes back -- and not all of it
// is a human reply. A MAILER-DAEMON bounce ("550 User Unknown"), an
// out-of-office autoresponder, and a real "sure, let's talk" all arrive as
// "some message not from us". Counting the first two as replies is exactly what
// inflates a reply rate into a number nobody can trust. So each inbound message
// is sorted into one of:
//
//   "reply"       - a genuine human reply (the ONLY thing that counts)
//   "bounced"     - HARD bounce: the address is wrong / does not exist
//   "soft_bounce" - a delivery failure that is not "wrong address" (mailbox
//                   full, temporarily blocked, greylisted, over quota)
//   "auto_reply"  - an automated response. The mailbox EXISTS, so it was
//                   delivered -- it is just not a reply.
//
// Detection uses only cheap header/snippet signals, never a full body fetch:
// From, Subject, Auto-Submitted, Content-Type, X-Failed-Recipients, Precedence,
// plus the provider's snippet. That is enough for the overwhelming majority of
// DSNs and vacation responders, and it keeps the cost of a reply check to one
// metadata request.

const lc = (s) => String(s || "").toLowerCase();

// A message is a delivery-status notification (a bounce of SOME kind) if it
// looks machine-generated by a mail system reporting a failure.
const BOUNCE_FROM =
  /(mailer-daemon|postmaster@|mail\s*delivery\s*(subsystem|system)|maildelivery|mail-daemon)/i;

const BOUNCE_SUBJECT =
  /(delivery status notification|undeliverable|undelivered mail returned|mail delivery (failed|failure)|delivery has failed|delivery failure|returned to sender|failure notice|could not be delivered|delivery incomplete|message not delivered|delivery report|returned mail|non-delivery)/i;

const BOUNCE_SNIPPET =
  /(wasn'?t delivered|was not delivered|couldn'?t be delivered|delivery to the following recipient(s)? failed|address (not found|couldn'?t be found)|recipient .*(rejected|not found)|unable to deliver)/i;

// HARD bounce -- the address itself is bad. High-confidence signals only, so a
// temporarily-failing but VALID address is never branded "wrong".
const HARD_BOUNCE =
  /(user unknown|no such user|address (not found|couldn'?t be found|rejected)|does not exist|doesn'?t exist|no such (address|recipient|mailbox)|recipient (address )?(rejected|not found|unknown)|unknown (recipient|user|address)|mailbox (unavailable|not found|does not exist)|account (has been )?(disabled|discontinued|closed|deactivated)|no mailbox|invalid (recipient|address|mailbox)|5\.1\.[013]|5\.0\.0|550[ -]?5\.1|551)/i;

// SOFT bounce -- a real delivery failure that is not "wrong address".
const SOFT_BOUNCE =
  /(mailbox (is )?full|over ?quota|quota exceeded|insufficient (system )?storage|temporar(il)?y|try again|greylist|rate limit(ed)?|too many|message (blocked|deferred|delayed)|spam|policy|4\.\d\.\d|421|450|451|452|552)/i;

// Auto-responder: the mailbox exists, but no human read it.
const AUTO_SUBJECT =
  /(out of (the )?office|out-of-office|automatic reply|auto[\s_-]?reply|autoresponder|on vacation|away from (the office|my desk|email)|currently (away|unavailable|out)|maternity leave|annual leave|parental leave)/i;

const AUTO_SUBMITTED = /(auto-replied|auto-generated|auto-notified)/i;
const AUTO_PRECEDENCE = /(auto_reply|bulk|junk|list)/i;

// A short human-readable reason for the UI, drawn from whatever signal exists.
const shortReason = (parts) => {
  const subject = String(parts.subject || "").trim();
  const snippet = String(parts.snippet || "").trim();
  const hay = `${subject} ${snippet}`;
  const m = hay.match(
    /5\.1\.[013]|550[^\n]{0,40}|user unknown|address (not found|couldn'?t be found)|does not exist|mailbox (unavailable|full)|over ?quota|no such (user|mailbox|address)/i
  );
  if (m) return m[0].slice(0, 120).trim();
  if (subject) return subject.slice(0, 120);
  return "delivery failed";
};

// parts: { from, subject, snippet, autoSubmitted, contentType,
//          xFailedRecipients, precedence }
// Returns { type, reason }.
const classifyInbound = (parts = {}) => {
  const from = lc(parts.from);
  const subject = lc(parts.subject);
  const snippet = lc(parts.snippet);
  const autoSub = lc(parts.autoSubmitted);
  const contentType = lc(parts.contentType);
  const xFailed = String(parts.xFailedRecipients || "").trim();
  const precedence = lc(parts.precedence);

  const looksLikeBounce =
    BOUNCE_FROM.test(from) ||
    !!xFailed ||
    /multipart\/report|delivery-status/.test(contentType) ||
    BOUNCE_SUBJECT.test(subject) ||
    BOUNCE_SNIPPET.test(snippet);

  if (looksLikeBounce) {
    const hay = `${subject} ${snippet}`;
    // Prefer a definite hard signal, then a definite soft one. A DSN we cannot
    // grade falls to SOFT: never falsely brand an address "wrong", because that
    // is a permanent judgement about a real person's contact details.
    if (HARD_BOUNCE.test(hay)) return { type: "bounced", reason: shortReason(parts) };
    if (SOFT_BOUNCE.test(hay)) return { type: "soft_bounce", reason: shortReason(parts) };
    return { type: "soft_bounce", reason: shortReason(parts) };
  }

  // Auto-submitted DSNs are caught above; what is left here is vacation and
  // autoresponder mail.
  const looksAuto =
    AUTO_SUBMITTED.test(autoSub) ||
    AUTO_SUBJECT.test(subject) ||
    AUTO_PRECEDENCE.test(precedence);
  if (looksAuto) return { type: "auto_reply", reason: "" };

  return { type: "reply", reason: "" };
};

// Convenience: pull the fields classifyInbound needs off a Gmail message
// object. `header` is services/gmail/mime.js#header.
const partsFromGmail = (msg, header) => ({
  from: header(msg.payload, "From"),
  subject: header(msg.payload, "Subject"),
  snippet: msg.snippet || "",
  autoSubmitted: header(msg.payload, "Auto-Submitted"),
  contentType: header(msg.payload, "Content-Type"),
  xFailedRecipients: header(msg.payload, "X-Failed-Recipients"),
  precedence: header(msg.payload, "Precedence"),
});

module.exports = { classifyInbound, partsFromGmail, shortReason };
